### ISSUE TITLE
El proyecto sigue vivo?

### ISSUE THREAD

**Issue by amatiasq** [BCN3D/BCN3DPlus-Firmware#10]
Tenemos [una Pull Request](https://github.com/BCN3D/BCN3DPlus-Firmware/pull/8) abierta desde hace casi año y medio y no ha habido discusión al respecto, por lo tanto supongo que el proyecto está abandonado, no?

**Comment by AlejandroGarcia92** [comment]
El proyecto está congelado a nivel de desarrollo.
